#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具生成。
//     執行時版本:2.0.50727.3053
//
//     對此檔案的更改可能會導致不正確的行為，並且如果
//     重新生成程式碼，這些更改將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoAsEnumerable
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="DbAddressBook")]
	public partial class FirstLinqToSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTabAddressBook(TabAddressBook instance);
    partial void UpdateTabAddressBook(TabAddressBook instance);
    partial void DeleteTabAddressBook(TabAddressBook instance);
    #endregion
		
		public FirstLinqToSqlDataContext() : 
				base(global::DemoAsEnumerable.Properties.Settings.Default.DbAddressBookConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FirstLinqToSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FirstLinqToSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FirstLinqToSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FirstLinqToSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TabAddressBook> TabAddressBook
		{
			get
			{
				return this.GetTable<TabAddressBook>();
			}
		}
	}
	
	[Table(Name="dbo.TabAddressBook")]
	public partial class TabAddressBook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ab_id;
		
		private string _ab_name;
		
		private string _ab_dub;
		
		private string _ab_sex;
		
		private System.Nullable<byte> _ab_age;
		
		private string _ab_add;
		
		private string _ab_com;
		
		private string _ab_tel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onab_idChanging(long value);
    partial void Onab_idChanged();
    partial void Onab_nameChanging(string value);
    partial void Onab_nameChanged();
    partial void Onab_dubChanging(string value);
    partial void Onab_dubChanged();
    partial void Onab_sexChanging(string value);
    partial void Onab_sexChanged();
    partial void Onab_ageChanging(System.Nullable<byte> value);
    partial void Onab_ageChanged();
    partial void Onab_addChanging(string value);
    partial void Onab_addChanged();
    partial void Onab_comChanging(string value);
    partial void Onab_comChanged();
    partial void Onab_telChanging(string value);
    partial void Onab_telChanged();
    #endregion
		
		public TabAddressBook()
		{
			OnCreated();
		}
		
		[Column(Storage="_ab_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ab_id
		{
			get
			{
				return this._ab_id;
			}
			set
			{
				if ((this._ab_id != value))
				{
					this.Onab_idChanging(value);
					this.SendPropertyChanging();
					this._ab_id = value;
					this.SendPropertyChanged("ab_id");
					this.Onab_idChanged();
				}
			}
		}
		
		[Column(Storage="_ab_name", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ab_name
		{
			get
			{
				return this._ab_name;
			}
			set
			{
				if ((this._ab_name != value))
				{
					this.Onab_nameChanging(value);
					this.SendPropertyChanging();
					this._ab_name = value;
					this.SendPropertyChanged("ab_name");
					this.Onab_nameChanged();
				}
			}
		}
		
		[Column(Storage="_ab_dub", DbType="VarChar(50)")]
		public string ab_dub
		{
			get
			{
				return this._ab_dub;
			}
			set
			{
				if ((this._ab_dub != value))
				{
					this.Onab_dubChanging(value);
					this.SendPropertyChanging();
					this._ab_dub = value;
					this.SendPropertyChanged("ab_dub");
					this.Onab_dubChanged();
				}
			}
		}
		
		[Column(Storage="_ab_sex", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string ab_sex
		{
			get
			{
				return this._ab_sex;
			}
			set
			{
				if ((this._ab_sex != value))
				{
					this.Onab_sexChanging(value);
					this.SendPropertyChanging();
					this._ab_sex = value;
					this.SendPropertyChanged("ab_sex");
					this.Onab_sexChanged();
				}
			}
		}
		
		[Column(Storage="_ab_age", DbType="TinyInt")]
		public System.Nullable<byte> ab_age
		{
			get
			{
				return this._ab_age;
			}
			set
			{
				if ((this._ab_age != value))
				{
					this.Onab_ageChanging(value);
					this.SendPropertyChanging();
					this._ab_age = value;
					this.SendPropertyChanged("ab_age");
					this.Onab_ageChanged();
				}
			}
		}
		
		[Column(Storage="_ab_add", DbType="VarChar(200)")]
		public string ab_add
		{
			get
			{
				return this._ab_add;
			}
			set
			{
				if ((this._ab_add != value))
				{
					this.Onab_addChanging(value);
					this.SendPropertyChanging();
					this._ab_add = value;
					this.SendPropertyChanged("ab_add");
					this.Onab_addChanged();
				}
			}
		}
		
		[Column(Storage="_ab_com", DbType="VarChar(200)")]
		public string ab_com
		{
			get
			{
				return this._ab_com;
			}
			set
			{
				if ((this._ab_com != value))
				{
					this.Onab_comChanging(value);
					this.SendPropertyChanging();
					this._ab_com = value;
					this.SendPropertyChanged("ab_com");
					this.Onab_comChanged();
				}
			}
		}
		
		[Column(Storage="_ab_tel", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ab_tel
		{
			get
			{
				return this._ab_tel;
			}
			set
			{
				if ((this._ab_tel != value))
				{
					this.Onab_telChanging(value);
					this.SendPropertyChanging();
					this._ab_tel = value;
					this.SendPropertyChanged("ab_tel");
					this.Onab_telChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
