#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具生成。
//     執行時版本:2.0.50727.3053
//
//     對此檔案的更改可能會導致不正確的行為，並且如果
//     重新生成程式碼，這些更改將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoLinqToSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="DbAddressBook")]
	public partial class AddresBookDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTabAddressBook(TabAddressBook instance);
    partial void UpdateTabAddressBook(TabAddressBook instance);
    partial void DeleteTabAddressBook(TabAddressBook instance);
    partial void InsertTabShoppingList(TabShoppingList instance);
    partial void UpdateTabShoppingList(TabShoppingList instance);
    partial void DeleteTabShoppingList(TabShoppingList instance);
    #endregion
		
		public AddresBookDataClassesDataContext() : 
				base(global::DemoLinqToSql.Properties.Settings.Default.DbAddressBookConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public AddresBookDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AddresBookDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AddresBookDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AddresBookDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ViewShoppingList> ViewShoppingList
		{
			get
			{
				return this.GetTable<ViewShoppingList>();
			}
		}
		
		public System.Data.Linq.Table<TabAddressBook> TabAddressBook
		{
			get
			{
				return this.GetTable<TabAddressBook>();
			}
		}
		
		public System.Data.Linq.Table<TabShoppingList> TabShoppingList
		{
			get
			{
				return this.GetTable<TabShoppingList>();
			}
		}
		
		[Function(Name="dbo.DeleteGuest")]
		public int DeleteGuest([Parameter(DbType="BigInt")] System.Nullable<long> uid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uid);
			return ((int)(result.ReturnValue));
		}
	}
	
	[Table(Name="dbo.ViewShoppingList")]
	public partial class ViewShoppingList
	{
		
		private string _sl_pname;
		
		private decimal _sl_price;
		
		private int _sl_amount;
		
		private string _sl_unit;
		
		private System.Nullable<System.DateTime> _sl_indate;
		
		private long _ab_id;
		
		private string _ab_name;
		
		private string _ab_dub;
		
		private string _ab_sex;
		
		private System.Nullable<byte> _ab_age;
		
		private string _ab_add;
		
		private string _ab_com;
		
		private string _ab_tel;
		
		public ViewShoppingList()
		{
		}
		
		[Column(Storage="_sl_pname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sl_pname
		{
			get
			{
				return this._sl_pname;
			}
			set
			{
				if ((this._sl_pname != value))
				{
					this._sl_pname = value;
				}
			}
		}
		
		[Column(Storage="_sl_price", DbType="Money NOT NULL")]
		public decimal sl_price
		{
			get
			{
				return this._sl_price;
			}
			set
			{
				if ((this._sl_price != value))
				{
					this._sl_price = value;
				}
			}
		}
		
		[Column(Storage="_sl_amount", DbType="Int NOT NULL")]
		public int sl_amount
		{
			get
			{
				return this._sl_amount;
			}
			set
			{
				if ((this._sl_amount != value))
				{
					this._sl_amount = value;
				}
			}
		}
		
		[Column(Storage="_sl_unit", DbType="VarChar(10)")]
		public string sl_unit
		{
			get
			{
				return this._sl_unit;
			}
			set
			{
				if ((this._sl_unit != value))
				{
					this._sl_unit = value;
				}
			}
		}
		
		[Column(Storage="_sl_indate", DbType="DateTime")]
		public System.Nullable<System.DateTime> sl_indate
		{
			get
			{
				return this._sl_indate;
			}
			set
			{
				if ((this._sl_indate != value))
				{
					this._sl_indate = value;
				}
			}
		}
		
		[Column(Storage="_ab_id", DbType="BigInt NOT NULL")]
		public long ab_id
		{
			get
			{
				return this._ab_id;
			}
			set
			{
				if ((this._ab_id != value))
				{
					this._ab_id = value;
				}
			}
		}
		
		[Column(Storage="_ab_name", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ab_name
		{
			get
			{
				return this._ab_name;
			}
			set
			{
				if ((this._ab_name != value))
				{
					this._ab_name = value;
				}
			}
		}
		
		[Column(Storage="_ab_dub", DbType="VarChar(50)")]
		public string ab_dub
		{
			get
			{
				return this._ab_dub;
			}
			set
			{
				if ((this._ab_dub != value))
				{
					this._ab_dub = value;
				}
			}
		}
		
		[Column(Storage="_ab_sex", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string ab_sex
		{
			get
			{
				return this._ab_sex;
			}
			set
			{
				if ((this._ab_sex != value))
				{
					this._ab_sex = value;
				}
			}
		}
		
		[Column(Storage="_ab_age", DbType="TinyInt")]
		public System.Nullable<byte> ab_age
		{
			get
			{
				return this._ab_age;
			}
			set
			{
				if ((this._ab_age != value))
				{
					this._ab_age = value;
				}
			}
		}
		
		[Column(Storage="_ab_add", DbType="VarChar(200)")]
		public string ab_add
		{
			get
			{
				return this._ab_add;
			}
			set
			{
				if ((this._ab_add != value))
				{
					this._ab_add = value;
				}
			}
		}
		
		[Column(Storage="_ab_com", DbType="VarChar(200)")]
		public string ab_com
		{
			get
			{
				return this._ab_com;
			}
			set
			{
				if ((this._ab_com != value))
				{
					this._ab_com = value;
				}
			}
		}
		
		[Column(Storage="_ab_tel", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ab_tel
		{
			get
			{
				return this._ab_tel;
			}
			set
			{
				if ((this._ab_tel != value))
				{
					this._ab_tel = value;
				}
			}
		}
	}
	
	[Table(Name="dbo.TabAddressBook")]
	public partial class TabAddressBook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ab_id;
		
		private string _ab_name;
		
		private string _ab_dub;
		
		private string _ab_sex;
		
		private System.Nullable<byte> _ab_age;
		
		private string _ab_add;
		
		private string _ab_com;
		
		private string _ab_tel;
		
		private EntitySet<TabShoppingList> _TabShoppingList;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onab_idChanging(long value);
    partial void Onab_idChanged();
    partial void Onab_nameChanging(string value);
    partial void Onab_nameChanged();
    partial void Onab_dubChanging(string value);
    partial void Onab_dubChanged();
    partial void Onab_sexChanging(string value);
    partial void Onab_sexChanged();
    partial void Onab_ageChanging(System.Nullable<byte> value);
    partial void Onab_ageChanged();
    partial void Onab_addChanging(string value);
    partial void Onab_addChanged();
    partial void Onab_comChanging(string value);
    partial void Onab_comChanged();
    partial void Onab_telChanging(string value);
    partial void Onab_telChanged();
    #endregion
		
		public TabAddressBook()
		{
			this._TabShoppingList = new EntitySet<TabShoppingList>(new Action<TabShoppingList>(this.attach_TabShoppingList), new Action<TabShoppingList>(this.detach_TabShoppingList));
			OnCreated();
		}
		
		[Column(Storage="_ab_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ab_id
		{
			get
			{
				return this._ab_id;
			}
			set
			{
				if ((this._ab_id != value))
				{
					this.Onab_idChanging(value);
					this.SendPropertyChanging();
					this._ab_id = value;
					this.SendPropertyChanged("ab_id");
					this.Onab_idChanged();
				}
			}
		}
		
		[Column(Storage="_ab_name", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string ab_name
		{
			get
			{
				return this._ab_name;
			}
			set
			{
				if ((this._ab_name != value))
				{
					this.Onab_nameChanging(value);
					this.SendPropertyChanging();
					this._ab_name = value;
					this.SendPropertyChanged("ab_name");
					this.Onab_nameChanged();
				}
			}
		}
		
		[Column(Storage="_ab_dub", DbType="VarChar(50)")]
		public string ab_dub
		{
			get
			{
				return this._ab_dub;
			}
			set
			{
				if ((this._ab_dub != value))
				{
					this.Onab_dubChanging(value);
					this.SendPropertyChanging();
					this._ab_dub = value;
					this.SendPropertyChanged("ab_dub");
					this.Onab_dubChanged();
				}
			}
		}
		
		[Column(Storage="_ab_sex", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string ab_sex
		{
			get
			{
				return this._ab_sex;
			}
			set
			{
				if ((this._ab_sex != value))
				{
					this.Onab_sexChanging(value);
					this.SendPropertyChanging();
					this._ab_sex = value;
					this.SendPropertyChanged("ab_sex");
					this.Onab_sexChanged();
				}
			}
		}
		
		[Column(Storage="_ab_age", DbType="TinyInt")]
		public System.Nullable<byte> ab_age
		{
			get
			{
				return this._ab_age;
			}
			set
			{
				if ((this._ab_age != value))
				{
					this.Onab_ageChanging(value);
					this.SendPropertyChanging();
					this._ab_age = value;
					this.SendPropertyChanged("ab_age");
					this.Onab_ageChanged();
				}
			}
		}
		
		[Column(Storage="_ab_add", DbType="VarChar(200)")]
		public string ab_add
		{
			get
			{
				return this._ab_add;
			}
			set
			{
				if ((this._ab_add != value))
				{
					this.Onab_addChanging(value);
					this.SendPropertyChanging();
					this._ab_add = value;
					this.SendPropertyChanged("ab_add");
					this.Onab_addChanged();
				}
			}
		}
		
		[Column(Storage="_ab_com", DbType="VarChar(200)")]
		public string ab_com
		{
			get
			{
				return this._ab_com;
			}
			set
			{
				if ((this._ab_com != value))
				{
					this.Onab_comChanging(value);
					this.SendPropertyChanging();
					this._ab_com = value;
					this.SendPropertyChanged("ab_com");
					this.Onab_comChanged();
				}
			}
		}
		
		[Column(Storage="_ab_tel", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ab_tel
		{
			get
			{
				return this._ab_tel;
			}
			set
			{
				if ((this._ab_tel != value))
				{
					this.Onab_telChanging(value);
					this.SendPropertyChanging();
					this._ab_tel = value;
					this.SendPropertyChanged("ab_tel");
					this.Onab_telChanged();
				}
			}
		}
		
		[Association(Name="TabAddressBook_TabShoppingList", Storage="_TabShoppingList", ThisKey="ab_id", OtherKey="sl_abid")]
		public EntitySet<TabShoppingList> TabShoppingList
		{
			get
			{
				return this._TabShoppingList;
			}
			set
			{
				this._TabShoppingList.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TabShoppingList(TabShoppingList entity)
		{
			this.SendPropertyChanging();
			entity.TabAddressBook = this;
		}
		
		private void detach_TabShoppingList(TabShoppingList entity)
		{
			this.SendPropertyChanging();
			entity.TabAddressBook = null;
		}
	}
	
	[Table(Name="dbo.TabShoppingList")]
	public partial class TabShoppingList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _sl_id;
		
		private System.Nullable<long> _sl_abid;
		
		private string _sl_pname;
		
		private decimal _sl_price;
		
		private int _sl_amount;
		
		private string _sl_unit;
		
		private System.Nullable<System.DateTime> _sl_indate;
		
		private EntityRef<TabAddressBook> _TabAddressBook;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsl_idChanging(long value);
    partial void Onsl_idChanged();
    partial void Onsl_abidChanging(System.Nullable<long> value);
    partial void Onsl_abidChanged();
    partial void Onsl_pnameChanging(string value);
    partial void Onsl_pnameChanged();
    partial void Onsl_priceChanging(decimal value);
    partial void Onsl_priceChanged();
    partial void Onsl_amountChanging(int value);
    partial void Onsl_amountChanged();
    partial void Onsl_unitChanging(string value);
    partial void Onsl_unitChanged();
    partial void Onsl_indateChanging(System.Nullable<System.DateTime> value);
    partial void Onsl_indateChanged();
    #endregion
		
		public TabShoppingList()
		{
			this._TabAddressBook = default(EntityRef<TabAddressBook>);
			OnCreated();
		}
		
		[Column(Storage="_sl_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long sl_id
		{
			get
			{
				return this._sl_id;
			}
			set
			{
				if ((this._sl_id != value))
				{
					this.Onsl_idChanging(value);
					this.SendPropertyChanging();
					this._sl_id = value;
					this.SendPropertyChanged("sl_id");
					this.Onsl_idChanged();
				}
			}
		}
		
		[Column(Storage="_sl_abid", DbType="BigInt")]
		public System.Nullable<long> sl_abid
		{
			get
			{
				return this._sl_abid;
			}
			set
			{
				if ((this._sl_abid != value))
				{
					if (this._TabAddressBook.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsl_abidChanging(value);
					this.SendPropertyChanging();
					this._sl_abid = value;
					this.SendPropertyChanged("sl_abid");
					this.Onsl_abidChanged();
				}
			}
		}
		
		[Column(Storage="_sl_pname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sl_pname
		{
			get
			{
				return this._sl_pname;
			}
			set
			{
				if ((this._sl_pname != value))
				{
					this.Onsl_pnameChanging(value);
					this.SendPropertyChanging();
					this._sl_pname = value;
					this.SendPropertyChanged("sl_pname");
					this.Onsl_pnameChanged();
				}
			}
		}
		
		[Column(Storage="_sl_price", DbType="Money NOT NULL")]
		public decimal sl_price
		{
			get
			{
				return this._sl_price;
			}
			set
			{
				if ((this._sl_price != value))
				{
					this.Onsl_priceChanging(value);
					this.SendPropertyChanging();
					this._sl_price = value;
					this.SendPropertyChanged("sl_price");
					this.Onsl_priceChanged();
				}
			}
		}
		
		[Column(Storage="_sl_amount", DbType="Int NOT NULL")]
		public int sl_amount
		{
			get
			{
				return this._sl_amount;
			}
			set
			{
				if ((this._sl_amount != value))
				{
					this.Onsl_amountChanging(value);
					this.SendPropertyChanging();
					this._sl_amount = value;
					this.SendPropertyChanged("sl_amount");
					this.Onsl_amountChanged();
				}
			}
		}
		
		[Column(Storage="_sl_unit", DbType="VarChar(10)")]
		public string sl_unit
		{
			get
			{
				return this._sl_unit;
			}
			set
			{
				if ((this._sl_unit != value))
				{
					this.Onsl_unitChanging(value);
					this.SendPropertyChanging();
					this._sl_unit = value;
					this.SendPropertyChanged("sl_unit");
					this.Onsl_unitChanged();
				}
			}
		}
		
		[Column(Storage="_sl_indate", DbType="DateTime")]
		public System.Nullable<System.DateTime> sl_indate
		{
			get
			{
				return this._sl_indate;
			}
			set
			{
				if ((this._sl_indate != value))
				{
					this.Onsl_indateChanging(value);
					this.SendPropertyChanging();
					this._sl_indate = value;
					this.SendPropertyChanged("sl_indate");
					this.Onsl_indateChanged();
				}
			}
		}
		
		[Association(Name="TabAddressBook_TabShoppingList", Storage="_TabAddressBook", ThisKey="sl_abid", OtherKey="ab_id", IsForeignKey=true, DeleteRule="SET DEFAULT")]
		public TabAddressBook TabAddressBook
		{
			get
			{
				return this._TabAddressBook.Entity;
			}
			set
			{
				TabAddressBook previousValue = this._TabAddressBook.Entity;
				if (((previousValue != value) 
							|| (this._TabAddressBook.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TabAddressBook.Entity = null;
						previousValue.TabShoppingList.Remove(this);
					}
					this._TabAddressBook.Entity = value;
					if ((value != null))
					{
						value.TabShoppingList.Add(this);
						this._sl_abid = value.ab_id;
					}
					else
					{
						this._sl_abid = default(Nullable<long>);
					}
					this.SendPropertyChanged("TabAddressBook");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
