//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具生成。
//     執行時版本:2.0.50727.3053
//
//     對此檔案的更改可能會導致不正確的行為，並且如果
//     重新生成程式碼，這些更改將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoCheckWord {
    
    
    public partial class _Default {
        
        /// <summary>
        /// form1 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ScriptManager1 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// UpdatePanel1 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        /// <summary>
        /// ShowText 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ShowText;
        
        /// <summary>
        /// Label3 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label3;
        
        /// <summary>
        /// words 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox words;
        
        /// <summary>
        /// Label2 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label2;
        
        /// <summary>
        /// UserText 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox UserText;
        
        /// <summary>
        /// Ok 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Ok;
    }
}
