//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼由工具生成。
//     執行時版本:2.0.50727.3053
//
//     對此檔案的更改可能會導致不正確的行為，並且如果
//     重新生成程式碼，這些更改將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoRss {
    
    
    public partial class _Default {
        
        /// <summary>
        /// form1 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// RssLink 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink RssLink;
        
        /// <summary>
        /// Label2 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label2;
        
        /// <summary>
        /// RssComment 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox RssComment;
        
        /// <summary>
        /// Label3 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label3;
        
        /// <summary>
        /// chTitle 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox chTitle;
        
        /// <summary>
        /// Label4 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label4;
        
        /// <summary>
        /// chLink 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox chLink;
        
        /// <summary>
        /// Label5 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label5;
        
        /// <summary>
        /// chDescription 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox chDescription;
        
        /// <summary>
        /// sel 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList sel;
        
        /// <summary>
        /// GenBut 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button GenBut;
        
        /// <summary>
        /// MessageInfo 控件。
        /// </summary>
        /// <remarks>
        /// 自動生成的字段。
        /// 若要進行修改，請將字段聲明從設計器檔案移到程式碼隱藏檔案。
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label MessageInfo;
    }
}
